email_host: "localhost:3000"

default_time_zone: "Pacific Time (US & Canada)"
default_from_email: "nReduce <notifications@nreduce.com>"
default_reply_to_email: "nReduce Support <support@nreduce.com>"

client:
  test: "test"

location_options:
  - "San Francisco (downtown)"
  - "South Bay (Palo Alto, Mountain View, etc)"
  - "New York City"
  - "Seattle"
  - "Houston"
  - "London"
  - "Los Angeles"
  - "Amsterdam"
  - "Paris"
  - "Berlin"
  - "San Diego"
  - "Austin"
  - "San Diego"
  - "Washington DC"
  - "Other..."

startup_options:
  growth_model:
    "Not Sure Yet :)": 1
    "Viral": 2
    "SEO": 3
    "Advertising": 4
    "Partnerships": 5
    "SMB Sales": 6
    "Enterprise Sales": 7
  stage:
    "Idea": 1
    "Prototype": 2
    "Private Alpha/Beta": 3
    "Launched": 4
    "Generating Revenue/Scaling": 5
  company_goal:
    "Fun Project - Chatroulette": 1
    "Life Style Business - 4 Hour Workweek": 2
    "Steady Revenue - 37Signals": 3
    "Improve Society - Kiva": 4
    "Big Exit - Facebook": 5
  industry:
    - "Advertising"
    - "Analytics"
    - "Big Data"
    - "BioTech"
    - "Clean Tech"
    - "Consumer Web"
    - "Crowdsourcing"
    - "Digital Media"
    - "E-Commerce"
    - "Education"
    - "Energy"
    - "Enterprise Software"
    - "Entertainment"
    - "Facebook Applications"
    - "Fashion"
    - "Financial Services"
    - "Food and Beverages"
    - "Health and Wellness"
    - "Journalism"
    - "K-12 Education"
    - "Kids"
    - "Knowledge Management"
    - "Legal"
    - "Location Based Services"
    - "Manufacturing"
    - "Marketplaces"
    - "Mobile"
    - "Mobile Commerce"
    - "Mobile Games"
    - "Mobile Applications"
    - "Online Travel"
    - "Personal Health"
    - "Physical Goods"
    - "Professional Services"
    - "Real Estate"
    - "Recruiting"
    - "SaaS"
    - "Search"
    - "Security"
    - "Small Medium Businesses"
    - "Social Commerce"
    - "Social Games"
    - "Social Media"
    - "Transportation"
    - "University Students"
    - "Ventures for Good"
    - "Video"


yes_no_options:
  -
    - "Yes"
    - true
  -
    - "No"
    - false


agree_options:
  -
    - "Agree"
    - true
  -
    - "Disagree"
    - false

q1: "Are you free on Tuesday evenings (in your timezone) to meet with other entrepreneurs (either in person or virtually)?"
q2: "Does someone on your team know how to code?"
q3: "Do you feel that with your current team can make ship product updates and/or make meaningful customer traction every week?"
q4: "Do you have more than one founder on your team?"
q5: "Are you and all your cofounders willing to commit fulltime to your startup this summer?"
q6: "nReduce is about bringing elite startups together, not about forming startups. nReduce can not help recruit or add team members. Teams that can't make progress with their current team will not be able to finish the program. nReduce can not provide recruiting services for our startups."
q7: "nReduce startups only have to share what they feel comfortable sharing about their startups. You'll never be forced to tell other startups specific proprietary information or trade secret information about your company. However, sharing your general weekly progress, and what you've shipped (even without specifics) is required."


apis:
  twitter:
    consumer_key: "mkjNMEzcfmMCafueNVBGQ"
    consumer_secret: "KBtQ80iGRY5ivG6RVDOv2p8uoYAdLIRTTL5KKHnLLRY"
    oauth_token: "568897631-gQfh7J3ivGftKyxU5h18tsyi7c3vYmCrcwdI8c"
    oauth_token_secret: "fcO0nSIRf6hp1r1CchN21fd1cNfGfktPc6Vcwn8VpY"

  mailchimp:
    enabled: false
    everyone_list_id: ""
    investor_list_id: ""
    startup_list_id: ""
    mentor_list_id: ""

  hipchat:
    token: "19456f5350542b41a8651552e5ea16"

  google:
    key: "AIzaSyB_nTXn-pHI6KBTiKLthpk2o8CwBJsdcnQ"

  linkedin:
    key: 'dlvvu7wj3crq'
    secret_key: 'FEoK8dhge3JbczQe'

  tokbox:
    key: '17419732'
    secret: 'd6694363f2ad9b07e9093a5bb6ca8065209a31fd'

aws:
  s3:
    access_key_id: 'AKIAIBBRV3NRIKHCXYYQ'
    secret_access_key: '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'
    bucket: 'assets.nreduce.com'

paperclip_config:
  url: "/:class/:style/:updated_at.:extension"
  path: "/:class/:style/:updated_at.:extension"
  hash_secret: "6S0Z6CwVt7w1zPYpomycLFL9rTffnzGBDtCBhqcXJIrdmHWUwCQHdbKq4f5AMjt"
  styles:
    medium: '250x250>'
    thumb: '120x120#'