production:
  solr:
    hostname: localhost
    port: 8683
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8682
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8681
    log_level: WARNING