site_url: "http://www.nreduce.com"
email_host: "nreduce.com"

apis:
  twitter:
    consumer_key: "Rn8g642gGKo8hv6fn1xYQ"
    consumer_secret: "tnRZYSjmGZKUBMzinDe8YKZMcsUFq0zUAT8J4UT8"
    oauth_token: "568897631-pIJPlDWPUXB5dvTXv40wXCJrXsQCXFjrXTkAyMzc"
    oauth_token_secret: "K5eL5zLqfJENKvNyGdEJjlcArkDgsqUCtXxgXNS8U"

  mailchimp:
    enabled: true
    api_key: "cf1fbea231f5330dbda47c72f151077e-us5"
    everyone_list_id: "e67395ae74"
    startup_list_id: ""
    mentor_list_id: ""
    investor_list_id: ""

smtp_settings:
  address: 'smtp.sendgrid.net'
  port: 587
  domain: 'nreduce.com'
  user_name: 'nreduce'
  password: 'th3dudeabides'
  authentication: 'plain'
  enable_starttls_auto: true

